### ISSUE TITLE
Inputin tarkistaminen kaatuu

### ISSUE THREAD

**Issue by niilopoutanen** [niilopoutanen/TODO-app_android#23]
Liian iso kuukausi & päivä kaataa tarkistuksen, saattaa olla jossakin muussakin kohtaa vikaa
![image](https://user-images.githubusercontent.com/60819607/193408865-b27359f8-1b98-4894-9e35-7fc1705fffe7.png)

![Screenshot_20221001-150838_TODO-app](https://user-images.githubusercontent.com/60819607/193408904-0634af35-dc96-4f2f-a17e-9e4dc5449389.jpg)

**Comment by osaama05** [comment]
Pitäs olla korjattu (Lisäsin vaan checkit liian isolle/pienelle kuukaudelle ja vuodelle)
